version: 0.2

phases:
  install:
    commands:
      - wget -nv https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome-stable_current_amd64.deb
      - apt-get install -y markdown nodejs
      - npm install chrome-headless-render-pdf
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - make
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '*.pdf'
  name: resume-${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/}
